sonar.projectKey=emmelf
sonar.organization=emmelf
sonar.projectName=Through-line

sonar.sources=api/src,web-app/src
sonar.tests=api/tests
sonar.exclusions=api/vendor/**,api/var/**,web-app/node_modules/**,.github/**,.idea/**
sonar.test.inclusions=api/tests/**/*.php
sonar.php.tests.reportPath=api/var/phpunit-junit.xml
